CREATE DATABASE IF NOT EXISTS autostock_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE autostock_db;
CREATE TABLE IF NOT EXISTS marcas (id BIGINT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(100) NOT NULL, CONSTRAINT uk_marca_nome UNIQUE(nome));
CREATE TABLE IF NOT EXISTS modelos (id BIGINT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(150) NOT NULL, marca_id BIGINT NOT NULL, CONSTRAINT uk_modelo_marca_nome UNIQUE(marca_id,nome), CONSTRAINT fk_modelo_marca FOREIGN KEY(marca_id) REFERENCES marcas(id));
CREATE TABLE IF NOT EXISTS veiculos (id BIGINT AUTO_INCREMENT PRIMARY KEY, modelo_id BIGINT NOT NULL, ano INT NOT NULL, cor VARCHAR(50) NOT NULL, preco DECIMAL(12,2) NOT NULL, quilometragem INT NOT NULL, status VARCHAR(50) NOT NULL, observacao VARCHAR(500), CONSTRAINT fk_veiculo_modelo FOREIGN KEY(modelo_id) REFERENCES modelos(id));
